# Generated by Django 4.1.5 on 2023-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leuci_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
    ]
