# Generated by Django 4.1.5 on 2023-01-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leuci_web', '0002_destination_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('destintations', models.ManyToManyField(related_name='destinations', to='leuci_web.destination')),
            ],
        ),
    ]
