# Generated by Django 4.1.6 on 2023-02-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leuci_web', '0004_gene_structure_inforequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='destintations',
        ),
        migrations.AddField(
            model_name='cruise',
            name='destinations',
            field=models.ManyToManyField(related_name='cruises', to='leuci_web.destination'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='slug',
            field=models.SlugField(default='x'),
            preserve_default=False,
        ),
    ]
